sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
addons:
  chrome: stable
  firefox: "45.0"
node_js:
  - "10"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test-and-cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
